{% set name = "openseries" %}
{% set version = "2.1.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openseries-{{ version }}.tar.gz
  sha256: e7433a5c36525d0deaad7fe99b4fb0b05eb72bd06c3ddb8fbd6e8dc840fd7e7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=69
    - wheel
  run:
    - python >={{ python_min }}
    - exchange-calendars >=4.8
    - holidays >=0.30
    - numpy >=1.23.2
    - openpyxl >=3.1.2
    - pandas >=2.1.2
    - plotly >=5.18.0
    - pydantic >=2.5.2
    - python-dateutil >=2.8.2
    - requests >=2.20.0
    - scipy >=1.14.1
    - scikit-learn >=1.4.0
    - python-tzdata >=2025.3

test:
  imports:
    - openseries
  commands:
    - python -c "import openseries; print(openseries.__version__)"
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - python-tzdata >=2025.3

about:
  home: https://captorab.github.io/openseries/
  summary: Tools to analyze financial timeseries.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://openseries.readthedocs.io
  dev_url: https://github.com/CaptorAB/openseries
  description: |
    Tools to analyze financial timeseries of single assets or portfolios. It is made for daily or less frequent data.

extra:
  recipe-maintainers:
    - karrmagadgeteer2
